#!/bin/sh

python${2} ../pareto.py --input in3_a.txt in3_b.txt in3_c.txt in3_d.txt in3_e.txt in3_f.txt --output ou3.txt --objectives 27 28 29 --epsilons 0.1 0.1 0.1 --delimiter=' ' --contribution ${1}
